version: "3"

services:
  sql-server:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password1
    ports:
    - "1433:1433"

networks:
  default:
    external:
      name: nat
