version: "3"

services:
  sqlserver:
    image: microsoft/mssql-server-windows-express:1709
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=password!123
    ports:
    - "1433:1433"

networks:
  default:
    external:
      name: nat
