variables:
- name: dotnetCoreSdkVersion
  value: 3.0.x
- name: dotnetCore21SdkVersion
  value: 2.1.x
- name: packageFeed
  value: /ffc32c57-3e0e-4e8f-8633-a7ad01df2e45
- name: publishOutput
  value: $(Build.SourcesDirectory)/src/bin/managed-publish
