job: managed
strategy:
  matrix:
    windows:
      imageName: windows-2019
    linux:
      imageName: ubuntu-16.04

pool:
  vmImage: $(imageName)

steps:
- task: UseDotNet@2
  displayName: install dotnet core sdk 3.1
  inputs:
    packageType: sdk
    version: 3.1.x

- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: restore
    projects: |
      src/**/*.csproj
    vstsFeed: $(packageFeed)

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: build
    configuration: $(buildConfiguration)
    projects: |
      src/**/*.csproj