version: '3'
services:
  datadog-agent:
    image: datadog/agent:latest
    environment:
    - DD_API_KEY=${DD_API_KEY}
    - DD_ENV=${DD_ENV}
    - DD_APM_ENABLED=true
    - DD_APM_NON_LOCAL_TRAFFIC=true
    - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
#  mock-agent:
#    image: mock-agent
#    build:
#      context: ../tools/Datadog.MockTraceAgent
  app-none:
    depends_on:
    - datadog-agent
    image: app-none
    build:
      context: ../
      dockerfile: performance/AspNetCore31/Dockerfile
      args:
      - DD_TRACER_VERSION=project
    environment:
    - DD_AGENT_HOST=datadog-agent
    - DD_SERVICE_NAME=app-none
    ports:
    - "127.0.0.1:60000:80"
  app-nuget:
    depends_on:
    - datadog-agent
    image: app-manual-${TRACER_VERSION}
    build:
      context: ../
      dockerfile: performance/AspNetCore31/Dockerfile
      args:
      - DD_TRACER_VERSION=${TRACER_VERSION}
    environment:
    - DD_AGENT_HOST=datadog-agent
    - DD_SERVICE_NAME=app-manual-${TRACER_VERSION}
    - DD_TRACER_VERSION=${TRACER_VERSION}
    - DD_MAX_MANUAL_SPANS=${MAX_MANUAL_SPANS}
    - DD_MAX_TAGS=${MAX_TAGS}
    ports:
    - "127.0.0.1:60002:80"
  app-branch:
    depends_on:
    - datadog-agent
    image: app-manual-branch
    build:
      context: ../
      dockerfile: performance/AspNetCore31/Dockerfile
      args:
      - DD_TRACER_VERSION=project
    environment:
    - DD_AGENT_HOST=datadog-agent
    - DD_SERVICE_NAME=app-manual-branch
    - DD_TRACER_VERSION=project
    - DD_MAX_MANUAL_SPANS=${MAX_MANUAL_SPANS}
    - DD_MAX_TAGS=${MAX_TAGS}
    ports:
    - "127.0.0.1:60004:80"
#  app-profiler:
#    depends_on:
#    - datadog-agent
#    image: app-with-profiler
#    build:
#      context: ../
#      dockerfile: performance/AspNetCore31/Dockerfile
#    environment:
#    - DD_SERVICE_NAME=app-with-profiler
#    - DD_AGENT_HOST=datadog-agent
#    - DD_TRACER_VERSION=${TRACER_VERSION}
#    - DD_MAX_MANUAL_SPANS=${MAX_MANUAL_SPANS}
#    - CORECLR_ENABLE_PROFILING=1
#    ports:
#    - "127.0.0.1:60005:80"
  http-requests-none:
    depends_on:
    - app-none
    image: http-requests
    build:
      context: http-requests/
    command: "dotnet http-requests.dll http://app-none:80 --rps ${REQUESTS_PER_SECOND}"
  http-requests-nuget:
    depends_on:
    - app-nuget
    image: http-requests
    build:
      context: http-requests/
    command: "dotnet http-requests.dll http://app-nuget:80 --rps ${REQUESTS_PER_SECOND}"
  http-requests-branch:
    depends_on:
    - app-branch
    image: http-requests
    build:
      context: http-requests/
    command: "dotnet http-requests.dll http://app-branch:80 --rps ${REQUESTS_PER_SECOND}"
