trigger:
  batch: 'true'
  branches:
    include:
      - bob/iis-testing
  paths:
    exclude:
      - docs/*
      - .github/*

variables:
  buildConfiguration: Release
  packageFeed: /ffc32c57-3e0e-4e8f-8633-a7ad01df2e45
  dotnetCoreSdkVersion: 3.0.x
  dotnetCore21SdkVersion: 2.1.x
  publishOutput: $(Build.SourcesDirectory)/src/bin/managed-publish

jobs:

- job: Windows

  pool:
    vmImage: windows-2019

  variables:
    buildPlatform: 'x64'

  steps:
  - task: UseDotNet@2
    displayName: install dotnet core 2.1 sdk
    inputs:
      packageType: sdk
      version: $(dotnetCore21SdkVersion)

  - task: DotNetCoreCLI@2
    displayName: dotnet build src/**/*.csproj
    inputs:
      command: build
      projects: |
        src/**/*.csproj
      arguments: --configuration $(buildConfiguration)

  - task: DotNetCoreCLI@2
    displayName: dotnet publish Datadog.Trace.ClrProfiler.Managed --framework net45
    inputs:
      command: publish
      publishWebProjects: false
      modifyOutputPath: false
      zipAfterPublish: false
      projects: src/Datadog.Trace.ClrProfiler.Managed/Datadog.Trace.ClrProfiler.Managed.csproj
      arguments: --configuration $(buildConfiguration) --framework net45 --output $(publishOutput)/net45

  - task: DotNetCoreCLI@2
    displayName: dotnet publish Datadog.Trace.ClrProfiler.Managed --framework net461
    inputs:
      command: publish
      publishWebProjects: false
      modifyOutputPath: false
      zipAfterPublish: false
      projects: src/Datadog.Trace.ClrProfiler.Managed/Datadog.Trace.ClrProfiler.Managed.csproj
      arguments: --configuration $(buildConfiguration) --framework net461 --output $(publishOutput)/net461

  - task: DotNetCoreCLI@2
    displayName: dotnet publish Datadog.Trace.ClrProfiler.Managed --framework netstandard2.0
    inputs:
      command: publish
      publishWebProjects: false
      modifyOutputPath: false
      zipAfterPublish: false
      projects: src/Datadog.Trace.ClrProfiler.Managed/Datadog.Trace.ClrProfiler.Managed.csproj
      arguments: --configuration $(buildConfiguration) --framework netstandard2.0 --output $(publishOutput)/netstandard2.0

  - task: NuGetCommand@2
    displayName: nuget restore native
    inputs:
      restoreSolution: Datadog.Trace.Native.sln
      vstsFeed: $(packageFeed)
      verbosityRestore: Normal

  - task: MSBuild@1
    displayName: msbuild native
    inputs:
      solution: Datadog.Trace.proj
      platform: $(buildPlatform)
      configuration: $(buildConfiguration)
      msbuildArguments: /t:BuildCpp
      maximumCpuCount: true

  - task: NuGetCommand@2
    displayName: 'nuget restore reproductions/**/packages.config'
    inputs:
      restoreSolution: reproductions/**/packages.config
      restoreDirectory: $(Build.SourcesDirectory)/packages
      vstsFeed: $(packageFeed)
      verbosityRestore: Normal

  - task: MSBuild@1
    displayName: 'Build .NET Framework projects (not SDK-based projects)'
    inputs:
      solution: Datadog.Trace.proj
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      msbuildArguments: '/t:BuildFrameworkReproductions'
      maximumCpuCount: true

  - task: MSBuild@1
    displayName: msbuild MSI
    inputs:
      solution: Datadog.Trace.proj
      platform: x64
      configuration: Release
      msbuildArguments: /t:msi /p:Configuration=Release;Platform=x64
      maximumCpuCount: True

  - task: PowerShell@2
    displayName: 'Create IIS web applications and install .NET Tracer'
    filePath: 'samples-aspnet\scripts\prepIISTesting.ps1'
    workingDirectory: 'samples-aspnet\scripts'
    failOnStderr: True
    errorActionPreference: stop

  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: test
      configuration: $(buildConfiguration)
      projects: test/Datadog.Trace.ClrProfiler.IntegrationTests/Datadog.Trace.ClrProfiler.IntegrationTests.csproj
      arguments: '--filter "RunOnWindows=True|Category=Smoke" -p:Platform=$(buildPlatform)'
