trigger:
  batch: 'true'
  branches:
    include:
      - refs/heads/*
  paths:
    exclude:
      - docs/*
      - .github/*

variables:
  - name: buildConfiguration
    value: Debug
  - template: templates/variables/build.yml

jobs:

- job: managed
  strategy:
    matrix:
      windows:
        imageName: windows-2019
      linux:
        imageName: ubuntu-16.04

  pool:
    vmImage: $(imageName)

  steps:
  - template: templates/steps/build-managed.yml

  - task: DotNetCoreCLI@2
    displayName: dotnet restore unit-tests
    inputs:
      command: restore
      projects: |
        test/**/*.Tests.csproj
      vstsFeed: $(packageFeed)

  - task: DotNetCoreCLI@2
    displayName: dotnet build unit-tests
    inputs:
      command: build
      configuration: $(buildConfiguration)
      projects: |
        test/**/*.Tests.csproj

  - task: DotNetCoreCLI@2
    displayName: dotnet test unit-tests
    inputs:
      command: test
      configuration: $(buildConfiguration)
      projects: test/**/*.Tests.csproj

- job: native_windows
  strategy:
    matrix:
      x64:
        buildPlatform: x64
      x86:
        buildPlatform: x86

  pool:
    vmImage: windows-2019

  steps:
  - task: UseDotNet@2
    displayName: install dotnet core 2.1 sdk
    inputs:
      packageType: sdk
      version: $(dotnetCore21SdkVersion)

  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: build
      configuration: $(buildConfiguration)
      projects: |
        src/Datadog.Trace.ClrProfiler.Managed.Loader/Datadog.Trace.ClrProfiler.Managed.Loader.csproj
        sample-libs/**/Samples.ExampleLibrary*.csproj

  - task: NuGetCommand@2
    displayName: nuget restore
    inputs:
      restoreSolution: Datadog.Trace.Native.sln
      vstsFeed: $(packageFeed)
      verbosityRestore: Normal

  - task: MSBuild@1
    displayName: msbuild
    inputs:
      solution: Datadog.Trace.proj
      platform: $(buildPlatform)
      configuration: $(buildConfiguration)
      msbuildArguments: /t:BuildCpp;BuildCppTests
      maximumCpuCount: true

  - script: Datadog.Trace.ClrProfiler.Native.Tests.exe --gtest_output=xml
    displayName: run tests
    workingDirectory: $(System.DefaultWorkingDirectory)/test/Datadog.Trace.ClrProfiler.Native.Tests/bin/$(buildConfiguration)/$(buildPlatform)

  - task: PublishTestResults@2
    displayName: publish test results
    inputs:
      testResultsFiles: test/**/test*.xml
      buildPlatform: $(buildPlatform)
      buildConfiguration: $(buildConfiguration)
    condition: succeededOrFailed()
